const fs = require("fs");
const path = require("path");

const webRoot = path.join(__dirname, "..");
const contentDir = path.join(webRoot, "content", "journal");
const outFile = path.join(webRoot, "src", "lib", "content", "journal-markdown.generated.ts");

const CATEGORY_MAP = {
  "brand + identity": "brand",
  brand: "brand",
  "voice + messaging": "voice",
  voice: "voice",
  "pr + comms": "pr",
  pr: "pr",
  growth: "growth",
  studio: "studio",
};

const AUTHOR_DISCIPLINE = {
  marcus: "voice + messaging",
  sarah: "brand + identity",
  george: "pr + communications",
  melissa: "product + growth",
  shane: "delivery + strategy",
};

const PUBLISH_SCHEDULE = {
  "better-told-brand-wins": "2026-06-03",
  "what-a-brand-strategy-agency-does": "2026-06-03",
  "weak-brand-paid-growth": "2026-06-03",
  "choosing-a-rebrand-agency-uk": "2026-06-10",
  "startup-pr-without-retainer": "2026-06-10",
  "brand-identity-for-startups": "2026-06-17",
  "tone-of-voice-underpriced-asset": "2026-06-17",
  "brand-guidelines-people-use": "2026-06-24",
  "messaging-framework-how-to": "2026-06-24",
  "website-copywriting-that-converts": "2026-07-01",
  "product-launch-pr-checklist": "2026-07-01",
  "ux-writing-is-brand-voice": "2026-07-08",
  "thought-leadership-without-cringe": "2026-07-08",
  "seo-for-new-brands": "2026-07-15",
  "landing-page-ux-five-seconds": "2026-07-15",
  "design-systems-small-teams": "2026-07-22",
  "one-team-vs-five-agencies": "2026-07-22",
};

function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return null;
  const data = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    data[key] = value;
  }
  return { data, body: match[2].trim() };
}

function stripMdInline(text) {
  return text.replace(/\*\*([^*]+)\*\*/g, "$1").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");
}

function markdownToBlocks(md) {
  const blocks = [];
  const lines = md.split("\n");
  let paragraph = [];

  const flush = () => {
    if (!paragraph.length) return;
    const text = stripMdInline(paragraph.join(" ").trim());
    if (text) blocks.push({ _type: "block", children: [{ text }] });
    paragraph = [];
  };

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      flush();
      continue;
    }
    if (trimmed.startsWith("# ")) continue;
    if (trimmed.startsWith("## ")) {
      flush();
      blocks.push({ _type: "heading", text: stripMdInline(trimmed.slice(3)) });
      continue;
    }
    if (trimmed.startsWith("> ")) continue;
    paragraph.push(trimmed);
  }
  flush();
  return blocks;
}

function categoryKey(category) {
  return CATEGORY_MAP[category.toLowerCase()] ?? "studio";
}

function wordCountFromBlocks(blocks) {
  const text = blocks
    .map((b) => {
      if (b.children) return b.children.map((c) => c.text).join(" ");
      return b.text ?? "";
    })
    .join(" ");
  return text.split(/\s+/).filter(Boolean).length;
}

function readingTimeFromBlocks(blocks) {
  const words = wordCountFromBlocks(blocks);
  return Math.max(1, Math.ceil(words / 200));
}

function compile() {
  if (!fs.existsSync(contentDir)) {
    fs.writeFileSync(outFile, "export const markdownJournalPosts = [] as const;\n");
    console.log("No content/journal — wrote empty journal-markdown.generated.ts");
    return;
  }

  const posts = [];
  for (const file of fs.readdirSync(contentDir).filter((f) => f.endsWith(".md"))) {
    const parsed = parseFrontmatter(fs.readFileSync(path.join(contentDir, file), "utf8"));
    if (!parsed) continue;
    const { data, body } = parsed;
    const authorSlug = data.author.toLowerCase();
    const cat = categoryKey(data.category);
    const publishedAt = PUBLISH_SCHEDULE[data.slug] ?? data.date;

    const bodyBlocks = markdownToBlocks(body);
    posts.push({
      slug: data.slug,
      title: data.title,
      category: cat,
      excerpt: data.excerpt,
      publishedAt,
      readingTime: readingTimeFromBlocks(bodyBlocks),
      featured: String(data.featured) === "true",
      author: { name: authorSlug, discipline: AUTHOR_DISCIPLINE[authorSlug] },
      body: bodyBlocks,
      seo: { metaDescription: data.excerpt },
    });
  }

  posts.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));

  const source = `/* auto-generated by scripts/compile-journal.js — do not edit */\nimport type { JournalPost } from "@/lib/types";\n\nexport const markdownJournalPosts: JournalPost[] = ${JSON.stringify(posts, null, 2)};\n`;
  fs.writeFileSync(outFile, source);
  console.log(`Compiled ${posts.length} journal posts to journal-markdown.generated.ts`);
}

compile();
